# Generated by Django 4.1.3 on 2022-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_carmodel_options_remove_order_estimate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimate_date',
            field=models.DateField(blank=True, null=True, verbose_name='estimate date'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('a', 'advance payemnt taken'), ('o', 'ordered parts'), ('w', 'working'), ('d', 'done'), ('c', 'cancelled'), ('p', 'paid')], default='n', max_length=1, verbose_name='status'),
        ),
    ]
