# Generated by Django 4.1.3 on 2022-11-18 11:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_order_return_date_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='non_standart_parts',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='non standart parts'),
        ),
    ]
