# Generated by Django 4.1.3 on 2022-11-21 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0012_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
